# Generated by Django 2.2.19 on 2021-09-04 23:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Название компании')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('address', models.TextField(blank=True, null=True, verbose_name='Адрес')),
                ('administrator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='companies', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='ФИО')),
                ('position', models.CharField(max_length=40, verbose_name='Долженость')),
                ('personal_phone', models.CharField(blank=True, max_length=15, null=True, verbose_name='Личный номер')),
                ('fax_phone', models.CharField(blank=True, max_length=15, null=True, verbose_name='Факс номер')),
                ('work_phone', models.CharField(blank=True, max_length=15, null=True, verbose_name='Рабочий номер')),
                ('company', models.ForeignKey(on_delete='Компания', related_name='workers', to='api.Company')),
            ],
        ),
        migrations.CreateModel(
            name='AccessPrivilege',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delegate_persons', to='api.Company')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='worker',
            constraint=models.UniqueConstraint(fields=('company', 'name'), name='unique_name'),
        ),
        migrations.AddConstraint(
            model_name='worker',
            constraint=models.UniqueConstraint(fields=('company', 'personal_phone'), name='unique_phone'),
        ),
        migrations.AddConstraint(
            model_name='accessprivilege',
            constraint=models.UniqueConstraint(fields=('user', 'company'), name='unique_permission'),
        ),
    ]
