# Generated by Django 2.2.19 on 2021-09-04 23:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='worker',
            name='unique_phone',
        ),
    ]
