# Generated by Django 2.2.19 on 2021-09-07 00:11

import api.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20210905_1601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='name',
            field=models.CharField(max_length=50, validators=[api.validators.validate_name], verbose_name='ФИО'),
        ),
    ]
