# Generated by Django 2.2.19 on 2021-09-07 17:24

import api.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20210907_0311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='fax_phone',
            field=models.CharField(blank=True, max_length=15, null=True, validators=[api.validators.validate_phone], verbose_name='Факс номер'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='personal_phone',
            field=models.CharField(blank=True, max_length=15, null=True, validators=[api.validators.validate_phone], verbose_name='Личный номер'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='work_phone',
            field=models.CharField(blank=True, max_length=15, null=True, validators=[api.validators.validate_phone], verbose_name='Рабочий номер'),
        ),
    ]
